#pragma once

// Version / build-provenance reporting for the logosctl CLI.
//
// The real values come from logos_build_info.h, generated by nix/build-info.nix
// and dropped next to this header at build time (see flake.nix). A plain
// `cmake` build outside nix has no such header — the __has_include guard keeps
// those working, reporting an unversioned dev build.

#include <string>

#if __has_include("logos_build_info.h")
#  include "logos_build_info.h"
#  define LOGOSCORE_HAS_BUILD_INFO 1
#else
#  define LOGOSCORE_HAS_BUILD_INFO 0
#endif

namespace logosctl_version {

// The release version, or "dev" when unreleased (no VERSION file baked in).
inline std::string version() {
#if LOGOSCORE_HAS_BUILD_INFO
    const std::string v = LOGOS_BUILD_VERSION;
    return v.empty() ? "dev" : v;
#else
    return "dev";
#endif
}

// This repo's commit, with a "-dirty" suffix when built from a dirty tree.
inline std::string commit() {
#if LOGOSCORE_HAS_BUILD_INFO
    return LOGOS_BUILD_COMMIT;
#else
    return "unknown";
#endif
}

// Full multi-line banner printed by `logosctl --version`. No trailing newline.
// `toolName` is the binary asking: the two front-ends share this code but must
// each identify as themselves. Hardcoding one meant `logoscore --version`
// reported "logosctl", which is exactly the sort of thing nobody notices until
// a bug report cites the wrong tool.
inline std::string versionString(const char* toolName = "logosctl") {
    std::string out = std::string(toolName) + " version " + version();
#if LOGOSCORE_HAS_BUILD_INFO
    out += "\ncommit: " + commit();
    const std::string commits = LOGOS_BUILD_COMMITS;
    if (!commits.empty())
        out += "\ndependency commits:\n" + commits;
#else
    out += "\ncommit: unknown (no build info)";
#endif
    return out;
}

} // namespace logosctl_version
